name: ESLint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint-check:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=14' # Specify version 14 or any version >= 14

      - name: Install dependencies
        run: npm ci

      - name: ESLint check
        run: npm run lint

      - name: Check for ESLint errors
        run: |
          ESLINT_EXIT_CODE=0
          npx eslint . --max-warnings 0 --quiet || ESLINT_EXIT_CODE=$?
          if [ $ESLINT_EXIT_CODE -eq 0 ]; then
            echo "ESLint check passed!"
          else
            echo "ESLint check failed. Please fix the errors before pushing or merging."
            exit 1
          fi
