name: ESLint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint-check:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify version 14 or any version >= 14

      - name: Install dependencies
        run: npm install

      - name: Get changed files
        id: changed-files
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: ESLint check
        run: |
          changed_files="${{ steps.changed-files.outputs.files }}"
          if [ -n "$changed_files" ]; then
            echo "Running ESLint on changed files:"
            echo "$changed_files" | xargs npx eslint
          else
            echo "No changed files found. Skipping ESLint check."
          fi

      - name: Check for ESLint errors
        run: |
          changed_files="${{ steps.changed-files.outputs.files }}"
          if [ -n "$changed_files" ]; then
            npx eslint $changed_files --max-warnings 0 --quiet || exit 1
            echo "ESLint check passed!"
          else
            echo "No changed files found. Skipping ESLint check."
          fi
